version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project/linx-frontend/cicd
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

  ReloadSupervisor:
    - location: scripts/restart_supervisor.sh
      timeout: 300
      runas: ubuntu
