# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ubuntu/project/linx-frontend/cicd/
# hooks:
#   AfterInstall:
#     - location: scripts/deploy.sh
#       runas: ubuntu

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project/cicd
hooks:
  BeforeInstall:
    - location: /home/ubuntu/project/cicd/scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: /home/ubuntu/project/cicd/scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
